export const SET_NAME = 'USER/SET_NAME'
export const SET_COLOR = 'USER/SET_COLOR'
export const SET_ERROR = 'USER/SET_ERROR'
export const SET_STATUS = 'USER/SET_STATUS'
export const SET_ADMIN_TOKEN = 'USER/SET_ADMIN_TOKEN'
