export default function Tw() {
  return (
    <div>
      <div>
        <div className="bg-inherit">o</div>
        <div className="bg-current">o</div>
        <div className="bg-black">o</div>
        <div className="bg-white">o</div>
        <div className="bg-gray-50">o</div>
        <div className="bg-gray-100">o</div>
        <div className="bg-gray-200">o</div>
        <div className="bg-gray-300">o</div>
        <div className="bg-gray-400">o</div>
        <div className="bg-gray-500">o</div>
        <div className="bg-gray-600">o</div>
        <div className="bg-gray-700">o</div>
        <div className="bg-gray-800">o</div>
        <div className="bg-gray-900">o</div>
        <div className="bg-red-50">o</div>
        <div className="bg-red-100">o</div>
        <div className="bg-red-200">o</div>
        <div className="bg-red-300 border-l-red-300 ">o</div>
        <div className="bg-red-400">o</div>
        <div className="bg-red-500">o</div>
        <div className="bg-red-600 border-red-600">o</div>
        <div className="bg-red-700">o</div>
        <div className="bg-red-800">o</div>
        <div className="bg-red-900">o</div>
        <div className="bg-orange-50">o</div>
        <div className="bg-orange-100">o</div>
        <div className="bg-orange-200">o</div>
        <div className="bg-orange-300 border-l-orange-300 ">o</div>
        <div className="bg-orange-400">o</div>
        <div className="bg-orange-500">o</div>
        <div className="bg-orange-600 border-orange-600">o</div>
        <div className="bg-orange-700">o</div>
        <div className="bg-orange-800">o</div>
        <div className="bg-orange-900">o</div>
        <div className="bg-amber-50">o</div>
        <div className="bg-amber-100">o</div>
        <div className="bg-amber-200">o</div>
        <div className="bg-amber-300 border-l-amber-300  ">o</div>
        <div className="bg-amber-400">o</div>
        <div className="bg-amber-500">o</div>
        <div className="bg-amber-600 border-amber-600">o</div>
        <div className="bg-amber-700">o</div>
        <div className="bg-amber-800">o</div>
        <div className="bg-amber-900">o</div>
        <div className="bg-yellow-50">o</div>
        <div className="bg-yellow-100">o</div>
        <div className="bg-yellow-200">o</div>
        <div className="bg-yellow-300 border-l-yellow-300 ">o</div>
        <div className="bg-yellow-400">o</div>
        <div className="bg-yellow-500">o</div>
        <div className="bg-yellow-600 border-yellow-600">o</div>
        <div className="bg-yellow-700">o</div>
        <div className="bg-yellow-800">o</div>
        <div className="bg-yellow-900">o</div>
        <div className="bg-lime-50">o</div>
        <div className="bg-lime-100">o</div>
        <div className="bg-lime-200">o</div>
        <div className="bg-lime-300 border-l-lime-300 ">o</div>
        <div className="bg-lime-400">o</div>
        <div className="bg-lime-500">o</div>
        <div className="bg-lime-600 border-lime-600">o</div>
        <div className="bg-lime-700">o</div>
        <div className="bg-lime-800">o</div>
        <div className="bg-lime-900">o</div>
        <div className="bg-green-50">o</div>
        <div className="bg-green-100">o</div>
        <div className="bg-green-200">o</div>
        <div className="bg-green-300 border-l-green-300 ">o</div>
        <div className="bg-green-400">o</div>
        <div className="bg-green-500">o</div>
        <div className="bg-green-600 border-green-600">o</div>
        <div className="bg-green-700">o</div>
        <div className="bg-green-800">o</div>
        <div className="bg-green-900">o</div>
        <div className="bg-emerald-50">o</div>
        <div className="bg-emerald-100">o</div>
        <div className="bg-emerald-200">o</div>
        <div className="bg-emerald-300 border-l-emerald-300 ">o</div>
        <div className="bg-emerald-400">o</div>
        <div className="bg-emerald-500">o</div>
        <div className="bg-emerald-600 border-emerald-600">o</div>
        <div className="bg-emerald-700">o</div>
        <div className="bg-emerald-800">o</div>
        <div className="bg-emerald-900">o</div>
        <div className="bg-teal-50">o</div>
        <div className="bg-teal-100">o</div>
        <div className="bg-teal-200">o</div>
        <div className="bg-teal-300 border-l-teal-300 ">o</div>
        <div className="bg-teal-400">o</div>
        <div className="bg-teal-500">o</div>
        <div className="bg-teal-600 border-teal-600">o</div>
        <div className="bg-teal-700">o</div>
        <div className="bg-teal-800">o</div>
        <div className="bg-teal-900">o</div>
        <div className="bg-cyan-50">o</div>
        <div className="bg-cyan-100">o</div>
        <div className="bg-cyan-200">o</div>
        <div className="bg-cyan-300 border-l-cyan-300 ">o</div>
        <div className="bg-cyan-400">o</div>
        <div className="bg-cyan-500">o</div>
        <div className="bg-cyan-600 border-cyan-600">o</div>
        <div className="bg-cyan-700">o</div>
        <div className="bg-cyan-800">o</div>
        <div className="bg-cyan-900">o</div>
        <div className="bg-sky-50">o</div>
        <div className="bg-sky-100">o</div>
        <div className="bg-sky-200">o</div>
        <div className="bg-sky-300 border-l-sky-300 ">o</div>
        <div className="bg-sky-400">o</div>
        <div className="bg-sky-500">o</div>
        <div className="bg-sky-600 border-sky-600">o</div>
        <div className="bg-sky-700">o</div>
        <div className="bg-sky-800">o</div>
        <div className="bg-sky-900">o</div>
        <div className="bg-blue-50">o</div>
        <div className="bg-blue-100">o</div>
        <div className="bg-blue-200">o</div>
        <div className="bg-blue-300 border-l-blue-300 ">o</div>
        <div className="bg-blue-400">o</div>
        <div className="bg-blue-500">o</div>
        <div className="bg-blue-600 border-blue-600">o</div>
        <div className="bg-blue-700">o</div>
        <div className="bg-blue-800">o</div>
        <div className="bg-blue-900">o</div>
        <div className="bg-indigo-50">o</div>
        <div className="bg-indigo-100">o</div>
        <div className="bg-indigo-200">o</div>
        <div className="bg-indigo-300 border-l-indigo-300 ">o</div>
        <div className="bg-indigo-400">o</div>
        <div className="bg-indigo-500">o</div>
        <div className="bg-indigo-600 border-indigo-600">o</div>
        <div className="bg-indigo-700">o</div>
        <div className="bg-indigo-800">o</div>
        <div className="bg-indigo-900">o</div>
        <div className="bg-violet-50">o</div>
        <div className="bg-violet-100">o</div>
        <div className="bg-violet-200">o</div>
        <div className="bg-violet-300 border-l-violet-300 ">o</div>
        <div className="bg-violet-400">o</div>
        <div className="bg-violet-500">o</div>
        <div className="bg-violet-600 border-violet-600">o</div>
        <div className="bg-violet-700">o</div>
        <div className="bg-violet-800">o</div>
        <div className="bg-violet-900">o</div>
        <div className="bg-purple-50">o</div>
        <div className="bg-purple-100">o</div>
        <div className="bg-purple-200">o</div>
        <div className="bg-purple-300 border-l-purple-300 ">o</div>
        <div className="bg-purple-400">o</div>
        <div className="bg-purple-500">o</div>
        <div className="bg-purple-600 border-purple-600">o</div>
        <div className="bg-purple-700">o</div>
        <div className="bg-purple-800">o</div>
        <div className="bg-purple-900">o</div>
        <div className="bg-fuchsia-50">o</div>
        <div className="bg-fuchsia-100">o</div>
        <div className="bg-fuchsia-200">o</div>
        <div className="bg-fuchsia-300 border-l-fuchsia-300 ">o</div>
        <div className="bg-fuchsia-400">o</div>
        <div className="bg-fuchsia-500">o</div>
        <div className="bg-fuchsia-600 border-fuchsia-600">o</div>
        <div className="bg-fuchsia-700">o</div>
        <div className="bg-fuchsia-800">o</div>
        <div className="bg-fuchsia-900">o</div>
        <div className="bg-pink-50">o</div>
        <div className="bg-pink-100">o</div>
        <div className="bg-pink-200">o</div>
        <div className="bg-pink-300 border-l-pink-300 ">o</div>
        <div className="bg-pink-400">o</div>
        <div className="bg-pink-500">o</div>
        <div className="bg-pink-600 border-pink-600">o</div>
        <div className="bg-pink-700">o</div>
        <div className="bg-pink-800">o</div>
        <div className="bg-pink-900">o</div>
        <div className="bg-rose-50">o</div>
        <div className="bg-rose-100">o</div>
        <div className="bg-rose-200">o</div>
        <div className="bg-rose-300 border-l-rose-300 ">o</div>
        <div className="bg-rose-400">o</div>
        <div className="bg-rose-500">o</div>
        <div className="bg-rose-600 border-rose-600">o</div>
        <div className="bg-rose-700">o</div>
        <div className="bg-rose-800">o</div>
        <div className="bg-rose-900">o</div>
      </div>
    </div>
  )
}
